FROM debian:sid

ENV DEBIAN_FRONTEND=noninteractive

RUN \
    apt-get update \
    && apt-get dist-upgrade -y \
    && echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && apt-get install -y locales sudo systemd-sysv wget

VOLUME [ "/run" ]
ENTRYPOINT [ "/sbin/init" ]
